name: Deploy to frappadingue.github.io

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai di repository "blog"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config user.name "frappadingue"
          git config user.email "iamfrappadingue@gmail.com"
      
      - name: Copy files to frappadingue.github.io
        run: |
          mkdir frappadingue.github.io
          rsync -av --exclude=".git" . frappadingue.github.io/
      
      - name: Move to frappadingue.github.io directory
        run: cd frappadingue.github.io/
      
      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Update blog"
          git push https://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@github.com/frappadingue/frappadingue.github.io.git HEAD:main
