name: Deploy to frappadingue.github.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "frappadingue"
          git config --global user.email "iamfrappadingue@gmail.com"

      - name: Copy 'public' folder to frappadingue.github.io
        run: |
          # Ganti dengan direktori tempat file "frappadingue.github.io" diletakkan
          cd home/Documents/frappadingue.github.io

          # Hapus konten yang ada di dalam repositori "frappadingue.github.io" kecuali direktori .git
          find . -not -name '.git' -delete

          # Ganti dengan direktori tempat folder 'public' di repositori "blog" diletakkan
          cd home/Documents/blog

          # Salin folder 'public' ke direktori repositori "frappadingue.github.io"
          cp -r public/* ../frappadingue.github.io/

      - name: Commit and push changes
        run: |
          cd path/to/frappadingue.github.io
          git add .
          git commit -m "Update 'public' folder from blog repository"
          git push
