name: Deploy to frappadingue.github.io

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama pada repositori blog

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        # Ganti dengan perintah build Anda, jika diperlukan
        run: npm run build

      - name: Deploy to frappadingue.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ganti dengan direktori build Anda, jika diperlukan
          publish_branch: main  # Ganti dengan nama branch utama pada repositori "frappadingue.github.io"
